server:
  port: 10086
spring:
  mail:
    # 163
    host: smtp.qq.com
    port: 465
    username: 1974125399@qq.com
    password: eumzaleznupubdia
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test001?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  quartz:
    job-store-type: jdbc
#    jdbc:
#      initialize-schema: always

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
